site_name: monome for VCV Rack
site_url: https://dewb.github.io/monome-rack
repo_url: https://github.com/Dewb/monome-rack
nav:
  - Manual: 'index.md'
  - 'General Info':
    - Introduction: 'general/intro.md'
    - 'Connecting Devices': 'general/connections.md'
    - 'Voltage Standards': 'general/voltage.md'
    - 'Credits & License': "general/credits.md"
  - 'Core Modules':
    - Ansible: 'modules/ansible.md'
    - Earthsea: 'modules/earthsea.md'
    - Meadowphysics: 'modules/meadowphysics.md'
    - Teletype: 'modules/teletype.md'
    - 'White Whale': 'modules/whitewhale.md'
  - 'Accessory Modules':
    - 'Virtual Grids': 'modules/grids.md'
  - 'Getting Help':
    - Index: 'help.md'
  - 'Releases↗': 'https://github.com/Dewb/monome-rack/releases'
  - 'Library Page↗': 'https://library.vcvrack.com/monome'
theme:
  name: terminal
  locale: en
  custom_dir: docs/custom-theme
  features:
    - navigation.side.indexes
watch:
  - docs/custom-theme
docs_dir: docs/content
site_dir: build/docs
extra_css: [extra.css]
markdown_extensions:
  - toc:
      baselevel: "1"
      toc_depth: "3"
      permalink: false
  - attr_list
  - md_in_html
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
