#define cpu_irq_enable_level(level)  
#define cpu_irq_disable_level(level) 
#define cpu_irq_enable()   
#define irq_initialize_vectors()
#define Disable_global_interrupt()
#define Enable_global_interrupt()
