name: Build Experimental
on: 
  push:
    branches:
      - tt2020
    paths-ignore:
      - README.md
jobs:
  buildWindows:
    name: Build Branch for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Windows
        uses: ./.github/actions/build_win
        env: 
          RACK_SDK_VERSION: 1.1.6
      - name: Upload Windows Release
        uses: ./.github/actions/update_asset
        env: 
          ASSET_PATH: plugins-v1/monome-1.0.0-pre-win.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: experimental
  buildMac:
    name: Build Branch for Mac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Mac
        uses: ./.github/actions/build_mac
        env: 
          RACK_SDK_VERSION: 1.1.6
      - name: Upload Mac Release
        uses: ./.github/actions/update_asset
        env: 
          ASSET_PATH: plugins-v1/monome-1.0.0-pre-mac.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: experimental